apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: reportportal
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: reportportal
  project: default
  source:
    helm:
      releaseName: reportportal
      valueFiles:
        - values.yaml
        - ../../deployments/dev/sc-service-yul/values.reportportal.yaml
    path: charts/reportportal
    repoURL: https://github.com/triadcode/reporting
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
