apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: reportportal
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/triadcode/reporting
    targetRevision: HEAD
    path: chart
    helm:
      valueFiles:
        - values.yaml
        - values.reportportal.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: reportportal
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
